package model

// LlmComment represents a code review comment generated by the LLM.
type LlmComment struct {
	Path           string `json:"path"`
	Content        string `json:"content"`
	SuggestionCode string `json:"suggestion_code,omitempty"`
	ExistingCode   string `json:"existing_code,omitempty"`
	StartLine      int    `json:"start_line"`
	EndLine        int    `json:"end_line"`
	Thinking       string `json:"thinking,omitempty"`
	// Title is a short headline (≈5–8 words) for the finding. When set, the
	// PR-posting workflow renders it as a bold line above Content. Optional;
	// the workflow falls back to the first non-empty line of Content.
	Title string `json:"title,omitempty"`
	// Severity is "P1" / "P2" / "P3" — critical / warning / nit. When set,
	// the workflow prefixes Title with a shields.io badge so reviewers can
	// scan severities at a glance. Optional.
	Severity string `json:"severity,omitempty"`
}

// CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
type CodeReviewResult struct {
	RelevantFile      string `json:"relevant_file"`
	SuggestionContent string `json:"suggestion_content"`
	ExistingCode      string `json:"existing_code"`
	SuggestionCode    string `json:"suggestion_code"`
}
